services:
  movie-feed:
    image: ghcr.io/calum4/movie-feed:latest
    container_name: movie-feed
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      RUST_LOG: "info,movie_feed=debug"
      MOVIE_FEED.TMDB_TOKEN: "REPLACE_ME" # One of TMDB_TOKEN or TMDB_TOKEN_FILE is required
      #MOVIE_FEED.TMDB_TOKEN_FILE: "REPLACE_ME" # See above ^
      MOVIE_FEED.API.LISTEN_ADDRESS: "0.0.0.0" # default 127.0.0.1
      #MOVIE_FEED.API.LISTEN_PORT: 8080 # Optional, default 8080
      #MOVIE_FEED_CLIENT_IP_SOURCE: "REPLACE_ME" # Optional, default ConnectInfo https://docs.rs/axum-client-ip/1.1.3/axum_client_ip/enum.ClientIpSource.html
    read_only: true
    user: "65534:65534"
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    restart: unless-stopped
